/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'serviceTraining' : null } |
  { 'leadership' : null } |
  { 'businessTransformation' : null } |
  { 'professionalDevelopment' : null } |
  { 'aiSkills' : null };
export interface Message { 'content' : string, 'role' : string }
export interface Session {
  'id' : bigint,
  'messages' : Array<Message>,
  'recommendations' : Array<string>,
  'sessionId' : string,
}
export type Status = { 'active' : null } |
  { 'completed' : null } |
  { 'inquiry' : null };
export interface Struct {
  'id' : bigint,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'awardBody' : string,
  'category' : string,
}
export interface Struct__1 {
  'id' : bigint,
  'title' : string,
  'publishedDate' : Time,
  'type' : Type,
  'authorName' : string,
  'downloadUrl' : string,
  'abstract' : string,
}
export interface Struct__2 {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'description' : string,
  'level' : string,
  'isCorporateCustomizable' : boolean,
  'category' : Category,
  'corporateAlignment' : string,
}
export interface Struct__3 {
  'id' : bigint,
  'status' : Status,
  'description' : string,
  'customRequirements' : string,
  'companyName' : string,
  'programTitle' : string,
}
export interface Struct__4 {
  'id' : bigint,
  'issueDate' : Time,
  'certName' : string,
  'description' : string,
  'isVerified' : boolean,
  'credentialId' : string,
  'requirements' : string,
  'recipientName' : string,
}
export interface Struct__5 {
  'id' : bigint,
  'expiryDate' : [] | [Time],
  'description' : string,
  'dateGranted' : Time,
  'bodyName' : string,
  'accreditationType' : string,
}
export interface Struct__6 {
  'id' : bigint,
  'inquiryType' : Type__1,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'organization' : string,
}
export type Time = bigint;
export type Type = { 'orange' : null } |
  { 'white' : null } |
  { 'intelligence' : null };
export type Type__1 = { 'courseCustomization' : null } |
  { 'corporatePartnership' : null } |
  { 'enrollment' : null } |
  { 'general' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAIAdvisorMessage' : ActorMethod<[bigint, Message], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAIAdvisorSession' : ActorMethod<[string], bigint>,
  'createAccreditation' : ActorMethod<[Struct__5], bigint>,
  'createCertification' : ActorMethod<[Struct__4], bigint>,
  'createCorporateProgram' : ActorMethod<[Struct__3], bigint>,
  'createCourse' : ActorMethod<[Struct__2], bigint>,
  'createPublication' : ActorMethod<[Struct__1], bigint>,
  'createRecognition' : ActorMethod<[Struct], bigint>,
  'deleteAccreditation' : ActorMethod<[bigint], undefined>,
  'deleteCertification' : ActorMethod<[bigint], undefined>,
  'deleteCorporateProgram' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  'deletePublication' : ActorMethod<[bigint], undefined>,
  'deleteRecognition' : ActorMethod<[bigint], undefined>,
  'getAIAdvisorSession' : ActorMethod<[bigint], [] | [Session]>,
  'getAccreditation' : ActorMethod<[bigint], [] | [Struct__5]>,
  'getAllAccreditations' : ActorMethod<[], Array<Struct__5>>,
  'getAllCertifications' : ActorMethod<[], Array<Struct__4>>,
  'getAllCorporatePrograms' : ActorMethod<[], Array<Struct__3>>,
  'getAllCourses' : ActorMethod<[], Array<Struct__2>>,
  'getAllInquiries' : ActorMethod<[], Array<Struct__6>>,
  'getAllPublications' : ActorMethod<[], Array<Struct__1>>,
  'getAllRecognitions' : ActorMethod<[], Array<Struct>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertification' : ActorMethod<[bigint], [] | [Struct__4]>,
  'getCertificationsByRecipient' : ActorMethod<[string], Array<Struct__4>>,
  'getCorporateCustomizableCourses' : ActorMethod<[], Array<Struct__2>>,
  'getCorporateProgram' : ActorMethod<[bigint], [] | [Struct__3]>,
  'getCourse' : ActorMethod<[bigint], [] | [Struct__2]>,
  'getInquiry' : ActorMethod<[bigint], [] | [Struct__6]>,
  'getPublication' : ActorMethod<[bigint], [] | [Struct__1]>,
  'getPublicationByType' : ActorMethod<[Type], Array<Struct__1>>,
  'getRecognition' : ActorMethod<[bigint], [] | [Struct]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<[Struct__6], bigint>,
  'updateAIAdvisorRecommendations' : ActorMethod<
    [bigint, Array<string>],
    undefined
  >,
  'updateAccreditation' : ActorMethod<[bigint, Struct__5], undefined>,
  'updateCertification' : ActorMethod<[bigint, Struct__4], undefined>,
  'updateCorporateProgram' : ActorMethod<[bigint, Struct__3], undefined>,
  'updateCorporateProgramStatus' : ActorMethod<[bigint, Status], undefined>,
  'updateCourse' : ActorMethod<[bigint, Struct__2], undefined>,
  'updatePublication' : ActorMethod<[bigint, Struct__1], undefined>,
  'updateRecognition' : ActorMethod<[bigint, Struct], undefined>,
  'uploadCourseMaterial' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];