/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Struct__5 = IDL.Record({
  'id' : IDL.Nat,
  'expiryDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'dateGranted' : Time,
  'bodyName' : IDL.Text,
  'accreditationType' : IDL.Text,
});
export const Struct__4 = IDL.Record({
  'id' : IDL.Nat,
  'issueDate' : Time,
  'certName' : IDL.Text,
  'description' : IDL.Text,
  'isVerified' : IDL.Bool,
  'credentialId' : IDL.Text,
  'requirements' : IDL.Text,
  'recipientName' : IDL.Text,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'inquiry' : IDL.Null,
});
export const Struct__3 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'description' : IDL.Text,
  'customRequirements' : IDL.Text,
  'companyName' : IDL.Text,
  'programTitle' : IDL.Text,
});
export const Category = IDL.Variant({
  'serviceTraining' : IDL.Null,
  'leadership' : IDL.Null,
  'businessTransformation' : IDL.Null,
  'professionalDevelopment' : IDL.Null,
  'aiSkills' : IDL.Null,
});
export const Struct__2 = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'isCorporateCustomizable' : IDL.Bool,
  'category' : Category,
  'corporateAlignment' : IDL.Text,
});
export const Type = IDL.Variant({
  'orange' : IDL.Null,
  'white' : IDL.Null,
  'intelligence' : IDL.Null,
});
export const Struct__1 = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'publishedDate' : Time,
  'type' : Type,
  'authorName' : IDL.Text,
  'downloadUrl' : IDL.Text,
  'abstract' : IDL.Text,
});
export const Struct = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'awardBody' : IDL.Text,
  'category' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'messages' : IDL.Vec(Message),
  'recommendations' : IDL.Vec(IDL.Text),
  'sessionId' : IDL.Text,
});
export const Type__1 = IDL.Variant({
  'courseCustomization' : IDL.Null,
  'corporatePartnership' : IDL.Null,
  'enrollment' : IDL.Null,
  'general' : IDL.Null,
});
export const Struct__6 = IDL.Record({
  'id' : IDL.Nat,
  'inquiryType' : Type__1,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'organization' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAIAdvisorMessage' : IDL.Func([IDL.Nat, Message], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAIAdvisorSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createAccreditation' : IDL.Func([Struct__5], [IDL.Nat], []),
  'createCertification' : IDL.Func([Struct__4], [IDL.Nat], []),
  'createCorporateProgram' : IDL.Func([Struct__3], [IDL.Nat], []),
  'createCourse' : IDL.Func([Struct__2], [IDL.Nat], []),
  'createPublication' : IDL.Func([Struct__1], [IDL.Nat], []),
  'createRecognition' : IDL.Func([Struct], [IDL.Nat], []),
  'deleteAccreditation' : IDL.Func([IDL.Nat], [], []),
  'deleteCertification' : IDL.Func([IDL.Nat], [], []),
  'deleteCorporateProgram' : IDL.Func([IDL.Nat], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'deletePublication' : IDL.Func([IDL.Nat], [], []),
  'deleteRecognition' : IDL.Func([IDL.Nat], [], []),
  'getAIAdvisorSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
  'getAccreditation' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__5)], ['query']),
  'getAllAccreditations' : IDL.Func([], [IDL.Vec(Struct__5)], ['query']),
  'getAllCertifications' : IDL.Func([], [IDL.Vec(Struct__4)], ['query']),
  'getAllCorporatePrograms' : IDL.Func([], [IDL.Vec(Struct__3)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Struct__2)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Struct__6)], ['query']),
  'getAllPublications' : IDL.Func([], [IDL.Vec(Struct__1)], ['query']),
  'getAllRecognitions' : IDL.Func([], [IDL.Vec(Struct)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertification' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__4)], ['query']),
  'getCertificationsByRecipient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Struct__4)],
      ['query'],
    ),
  'getCorporateCustomizableCourses' : IDL.Func(
      [],
      [IDL.Vec(Struct__2)],
      ['query'],
    ),
  'getCorporateProgram' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__3)], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__2)], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__6)], ['query']),
  'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__1)], ['query']),
  'getPublicationByType' : IDL.Func([Type], [IDL.Vec(Struct__1)], ['query']),
  'getRecognition' : IDL.Func([IDL.Nat], [IDL.Opt(Struct)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func([Struct__6], [IDL.Nat], []),
  'updateAIAdvisorRecommendations' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateAccreditation' : IDL.Func([IDL.Nat, Struct__5], [], []),
  'updateCertification' : IDL.Func([IDL.Nat, Struct__4], [], []),
  'updateCorporateProgram' : IDL.Func([IDL.Nat, Struct__3], [], []),
  'updateCorporateProgramStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updateCourse' : IDL.Func([IDL.Nat, Struct__2], [], []),
  'updatePublication' : IDL.Func([IDL.Nat, Struct__1], [], []),
  'updateRecognition' : IDL.Func([IDL.Nat, Struct], [], []),
  'uploadCourseMaterial' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Struct__5 = IDL.Record({
    'id' : IDL.Nat,
    'expiryDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'dateGranted' : Time,
    'bodyName' : IDL.Text,
    'accreditationType' : IDL.Text,
  });
  const Struct__4 = IDL.Record({
    'id' : IDL.Nat,
    'issueDate' : Time,
    'certName' : IDL.Text,
    'description' : IDL.Text,
    'isVerified' : IDL.Bool,
    'credentialId' : IDL.Text,
    'requirements' : IDL.Text,
    'recipientName' : IDL.Text,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'inquiry' : IDL.Null,
  });
  const Struct__3 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'description' : IDL.Text,
    'customRequirements' : IDL.Text,
    'companyName' : IDL.Text,
    'programTitle' : IDL.Text,
  });
  const Category = IDL.Variant({
    'serviceTraining' : IDL.Null,
    'leadership' : IDL.Null,
    'businessTransformation' : IDL.Null,
    'professionalDevelopment' : IDL.Null,
    'aiSkills' : IDL.Null,
  });
  const Struct__2 = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'isCorporateCustomizable' : IDL.Bool,
    'category' : Category,
    'corporateAlignment' : IDL.Text,
  });
  const Type = IDL.Variant({
    'orange' : IDL.Null,
    'white' : IDL.Null,
    'intelligence' : IDL.Null,
  });
  const Struct__1 = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'publishedDate' : Time,
    'type' : Type,
    'authorName' : IDL.Text,
    'downloadUrl' : IDL.Text,
    'abstract' : IDL.Text,
  });
  const Struct = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'awardBody' : IDL.Text,
    'category' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'messages' : IDL.Vec(Message),
    'recommendations' : IDL.Vec(IDL.Text),
    'sessionId' : IDL.Text,
  });
  const Type__1 = IDL.Variant({
    'courseCustomization' : IDL.Null,
    'corporatePartnership' : IDL.Null,
    'enrollment' : IDL.Null,
    'general' : IDL.Null,
  });
  const Struct__6 = IDL.Record({
    'id' : IDL.Nat,
    'inquiryType' : Type__1,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'organization' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAIAdvisorMessage' : IDL.Func([IDL.Nat, Message], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAIAdvisorSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createAccreditation' : IDL.Func([Struct__5], [IDL.Nat], []),
    'createCertification' : IDL.Func([Struct__4], [IDL.Nat], []),
    'createCorporateProgram' : IDL.Func([Struct__3], [IDL.Nat], []),
    'createCourse' : IDL.Func([Struct__2], [IDL.Nat], []),
    'createPublication' : IDL.Func([Struct__1], [IDL.Nat], []),
    'createRecognition' : IDL.Func([Struct], [IDL.Nat], []),
    'deleteAccreditation' : IDL.Func([IDL.Nat], [], []),
    'deleteCertification' : IDL.Func([IDL.Nat], [], []),
    'deleteCorporateProgram' : IDL.Func([IDL.Nat], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'deletePublication' : IDL.Func([IDL.Nat], [], []),
    'deleteRecognition' : IDL.Func([IDL.Nat], [], []),
    'getAIAdvisorSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
    'getAccreditation' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__5)], ['query']),
    'getAllAccreditations' : IDL.Func([], [IDL.Vec(Struct__5)], ['query']),
    'getAllCertifications' : IDL.Func([], [IDL.Vec(Struct__4)], ['query']),
    'getAllCorporatePrograms' : IDL.Func([], [IDL.Vec(Struct__3)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Struct__2)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Struct__6)], ['query']),
    'getAllPublications' : IDL.Func([], [IDL.Vec(Struct__1)], ['query']),
    'getAllRecognitions' : IDL.Func([], [IDL.Vec(Struct)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertification' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__4)], ['query']),
    'getCertificationsByRecipient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Struct__4)],
        ['query'],
      ),
    'getCorporateCustomizableCourses' : IDL.Func(
        [],
        [IDL.Vec(Struct__2)],
        ['query'],
      ),
    'getCorporateProgram' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Struct__3)],
        ['query'],
      ),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__2)], ['query']),
    'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__6)], ['query']),
    'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Struct__1)], ['query']),
    'getPublicationByType' : IDL.Func([Type], [IDL.Vec(Struct__1)], ['query']),
    'getRecognition' : IDL.Func([IDL.Nat], [IDL.Opt(Struct)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func([Struct__6], [IDL.Nat], []),
    'updateAIAdvisorRecommendations' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateAccreditation' : IDL.Func([IDL.Nat, Struct__5], [], []),
    'updateCertification' : IDL.Func([IDL.Nat, Struct__4], [], []),
    'updateCorporateProgram' : IDL.Func([IDL.Nat, Struct__3], [], []),
    'updateCorporateProgramStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updateCourse' : IDL.Func([IDL.Nat, Struct__2], [], []),
    'updatePublication' : IDL.Func([IDL.Nat, Struct__1], [], []),
    'updateRecognition' : IDL.Func([IDL.Nat, Struct], [], []),
    'uploadCourseMaterial' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };