/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Struct {
    id: bigint;
    title: string;
    year: bigint;
    description: string;
    awardBody: string;
    category: string;
}
export type Time = bigint;
export interface Struct__6 {
    id: bigint;
    inquiryType: Type__1;
    name: string;
    submittedAt: Time;
    email: string;
    message: string;
    organization: string;
}
export interface Struct__4 {
    id: bigint;
    issueDate: Time;
    certName: string;
    description: string;
    isVerified: boolean;
    credentialId: string;
    requirements: string;
    recipientName: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Struct__3 {
    id: bigint;
    status: Status;
    description: string;
    customRequirements: string;
    companyName: string;
    programTitle: string;
}
export interface Struct__2 {
    id: bigint;
    title: string;
    duration: bigint;
    description: string;
    level: string;
    isCorporateCustomizable: boolean;
    category: Category;
    corporateAlignment: string;
}
export interface Session {
    id: bigint;
    messages: Array<Message>;
    recommendations: Array<string>;
    sessionId: string;
}
export interface Struct__5 {
    id: bigint;
    expiryDate?: Time;
    description: string;
    dateGranted: Time;
    bodyName: string;
    accreditationType: string;
}
export interface Message {
    content: string;
    role: string;
}
export interface Struct__1 {
    id: bigint;
    title: string;
    publishedDate: Time;
    type: Type;
    authorName: string;
    downloadUrl: string;
    abstract: string;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    serviceTraining = "serviceTraining",
    leadership = "leadership",
    businessTransformation = "businessTransformation",
    professionalDevelopment = "professionalDevelopment",
    aiSkills = "aiSkills"
}
export enum Status {
    active = "active",
    completed = "completed",
    inquiry = "inquiry"
}
export enum Type {
    orange = "orange",
    white = "white",
    intelligence = "intelligence"
}
export enum Type__1 {
    courseCustomization = "courseCustomization",
    corporatePartnership = "corporatePartnership",
    enrollment = "enrollment",
    general = "general"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAIAdvisorMessage(sessionId: bigint, message: Message): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAIAdvisorSession(sessionId: string): Promise<bigint>;
    createAccreditation(accreditation: Struct__5): Promise<bigint>;
    createCertification(certification: Struct__4): Promise<bigint>;
    createCorporateProgram(program: Struct__3): Promise<bigint>;
    createCourse(course: Struct__2): Promise<bigint>;
    createPublication(publication: Struct__1): Promise<bigint>;
    createRecognition(recognition: Struct): Promise<bigint>;
    deleteAccreditation(id: bigint): Promise<void>;
    deleteCertification(id: bigint): Promise<void>;
    deleteCorporateProgram(id: bigint): Promise<void>;
    deleteCourse(id: bigint): Promise<void>;
    deleteInquiry(id: bigint): Promise<void>;
    deletePublication(id: bigint): Promise<void>;
    deleteRecognition(id: bigint): Promise<void>;
    getAIAdvisorSession(sessionId: bigint): Promise<Session | null>;
    getAccreditation(id: bigint): Promise<Struct__5 | null>;
    getAllAccreditations(): Promise<Array<Struct__5>>;
    getAllCertifications(): Promise<Array<Struct__4>>;
    getAllCorporatePrograms(): Promise<Array<Struct__3>>;
    getAllCourses(): Promise<Array<Struct__2>>;
    getAllInquiries(): Promise<Array<Struct__6>>;
    getAllPublications(): Promise<Array<Struct__1>>;
    getAllRecognitions(): Promise<Array<Struct>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCertification(id: bigint): Promise<Struct__4 | null>;
    getCertificationsByRecipient(recipientName: string): Promise<Array<Struct__4>>;
    getCorporateCustomizableCourses(): Promise<Array<Struct__2>>;
    getCorporateProgram(id: bigint): Promise<Struct__3 | null>;
    getCourse(id: bigint): Promise<Struct__2 | null>;
    getInquiry(id: bigint): Promise<Struct__6 | null>;
    getPublication(id: bigint): Promise<Struct__1 | null>;
    getPublicationByType(pubType: Type): Promise<Array<Struct__1>>;
    getRecognition(id: bigint): Promise<Struct | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitInquiry(inquiry: Struct__6): Promise<bigint>;
    updateAIAdvisorRecommendations(sessionId: bigint, recommendations: Array<string>): Promise<void>;
    updateAccreditation(id: bigint, accreditation: Struct__5): Promise<void>;
    updateCertification(id: bigint, certification: Struct__4): Promise<void>;
    updateCorporateProgram(id: bigint, program: Struct__3): Promise<void>;
    updateCorporateProgramStatus(id: bigint, status: Status): Promise<void>;
    updateCourse(id: bigint, course: Struct__2): Promise<void>;
    updatePublication(id: bigint, publication: Struct__1): Promise<void>;
    updateRecognition(id: bigint, recognition: Struct): Promise<void>;
    uploadCourseMaterial(courseId: bigint, filePath: string): Promise<void>;
}
import type { Category as _Category, Session as _Session, Status as _Status, Struct as _Struct, Struct__1 as _Struct__1, Struct__2 as _Struct__2, Struct__3 as _Struct__3, Struct__4 as _Struct__4, Struct__5 as _Struct__5, Struct__6 as _Struct__6, Time as _Time, Type as _Type, Type__1 as _Type__1, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAIAdvisorMessage(arg0: bigint, arg1: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAIAdvisorMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAIAdvisorMessage(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAIAdvisorSession(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAIAdvisorSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAIAdvisorSession(arg0);
            return result;
        }
    }
    async createAccreditation(arg0: Struct__5): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAccreditation(to_candid_Struct__5_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAccreditation(to_candid_Struct__5_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCertification(arg0: Struct__4): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCertification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCertification(arg0);
            return result;
        }
    }
    async createCorporateProgram(arg0: Struct__3): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCorporateProgram(to_candid_Struct__3_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCorporateProgram(to_candid_Struct__3_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCourse(arg0: Struct__2): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(to_candid_Struct__2_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(to_candid_Struct__2_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPublication(arg0: Struct__1): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPublication(to_candid_Struct__1_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPublication(to_candid_Struct__1_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRecognition(arg0: Struct): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecognition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecognition(arg0);
            return result;
        }
    }
    async deleteAccreditation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccreditation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccreditation(arg0);
            return result;
        }
    }
    async deleteCertification(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCertification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCertification(arg0);
            return result;
        }
    }
    async deleteCorporateProgram(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCorporateProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCorporateProgram(arg0);
            return result;
        }
    }
    async deleteCourse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteInquiry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(arg0);
            return result;
        }
    }
    async deletePublication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublication(arg0);
            return result;
        }
    }
    async deleteRecognition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecognition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecognition(arg0);
            return result;
        }
    }
    async getAIAdvisorSession(arg0: bigint): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIAdvisorSession(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIAdvisorSession(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccreditation(arg0: bigint): Promise<Struct__5 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccreditation(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccreditation(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAccreditations(): Promise<Array<Struct__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccreditations();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccreditations();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCertifications(): Promise<Array<Struct__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCertifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCertifications();
            return result;
        }
    }
    async getAllCorporatePrograms(): Promise<Array<Struct__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCorporatePrograms();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCorporatePrograms();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCourses(): Promise<Array<Struct__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Struct__6>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublications(): Promise<Array<Struct__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublications();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublications();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecognitions(): Promise<Array<Struct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecognitions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecognitions();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertification(arg0: bigint): Promise<Struct__4 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertification(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertification(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificationsByRecipient(arg0: string): Promise<Array<Struct__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificationsByRecipient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificationsByRecipient(arg0);
            return result;
        }
    }
    async getCorporateCustomizableCourses(): Promise<Array<Struct__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCorporateCustomizableCourses();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCorporateCustomizableCourses();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCorporateProgram(arg0: bigint): Promise<Struct__3 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCorporateProgram(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCorporateProgram(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: bigint): Promise<Struct__2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiry(arg0: bigint): Promise<Struct__6 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiry(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiry(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublication(arg0: bigint): Promise<Struct__1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublication(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublication(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicationByType(arg0: Type): Promise<Array<Struct__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicationByType(to_candid_Type_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicationByType(to_candid_Type_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecognition(arg0: bigint): Promise<Struct | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecognition(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecognition(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: Struct__6): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(to_candid_Struct__6_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(to_candid_Struct__6_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAIAdvisorRecommendations(arg0: bigint, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAIAdvisorRecommendations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAIAdvisorRecommendations(arg0, arg1);
            return result;
        }
    }
    async updateAccreditation(arg0: bigint, arg1: Struct__5): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccreditation(arg0, to_candid_Struct__5_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccreditation(arg0, to_candid_Struct__5_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCertification(arg0: bigint, arg1: Struct__4): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCertification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCertification(arg0, arg1);
            return result;
        }
    }
    async updateCorporateProgram(arg0: bigint, arg1: Struct__3): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCorporateProgram(arg0, to_candid_Struct__3_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCorporateProgram(arg0, to_candid_Struct__3_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCorporateProgramStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCorporateProgramStatus(arg0, to_candid_Status_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCorporateProgramStatus(arg0, to_candid_Status_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCourse(arg0: bigint, arg1: Struct__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, to_candid_Struct__2_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, to_candid_Struct__2_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePublication(arg0: bigint, arg1: Struct__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublication(arg0, to_candid_Struct__1_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublication(arg0, to_candid_Struct__1_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRecognition(arg0: bigint, arg1: Struct): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecognition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecognition(arg0, arg1);
            return result;
        }
    }
    async uploadCourseMaterial(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCourseMaterial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCourseMaterial(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Struct__1_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Struct__1): Struct__1 {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Struct__2_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Struct__2): Struct__2 {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Struct__3_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Struct__3): Struct__3 {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Struct__5_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Struct__5): Struct__5 {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Struct__6_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Struct__6): Struct__6 {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Struct__5]): Struct__5 | null {
    return value.length === 0 ? null : from_candid_Struct__5_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Struct__4]): Struct__4 | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Struct__3]): Struct__3 | null {
    return value.length === 0 ? null : from_candid_Struct__3_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Struct__2]): Struct__2 | null {
    return value.length === 0 ? null : from_candid_Struct__2_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Struct__6]): Struct__6 | null {
    return value.length === 0 ? null : from_candid_Struct__6_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Struct__1]): Struct__1 | null {
    return value.length === 0 ? null : from_candid_Struct__1_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Struct]): Struct | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expiryDate: [] | [_Time];
    description: string;
    dateGranted: _Time;
    bodyName: string;
    accreditationType: string;
}): {
    id: bigint;
    expiryDate?: Time;
    description: string;
    dateGranted: Time;
    bodyName: string;
    accreditationType: string;
} {
    return {
        id: value.id,
        expiryDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.expiryDate)),
        description: value.description,
        dateGranted: value.dateGranted,
        bodyName: value.bodyName,
        accreditationType: value.accreditationType
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    description: string;
    customRequirements: string;
    companyName: string;
    programTitle: string;
}): {
    id: bigint;
    status: Status;
    description: string;
    customRequirements: string;
    companyName: string;
    programTitle: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n33(_uploadFile, _downloadFile, value.status),
        description: value.description,
        customRequirements: value.customRequirements,
        companyName: value.companyName,
        programTitle: value.programTitle
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    duration: bigint;
    description: string;
    level: string;
    isCorporateCustomizable: boolean;
    category: _Category;
    corporateAlignment: string;
}): {
    id: bigint;
    title: string;
    duration: bigint;
    description: string;
    level: string;
    isCorporateCustomizable: boolean;
    category: Category;
    corporateAlignment: string;
} {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        description: value.description,
        level: value.level,
        isCorporateCustomizable: value.isCorporateCustomizable,
        category: from_candid_Category_n38(_uploadFile, _downloadFile, value.category),
        corporateAlignment: value.corporateAlignment
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inquiryType: _Type__1;
    name: string;
    submittedAt: _Time;
    email: string;
    message: string;
    organization: string;
}): {
    id: bigint;
    inquiryType: Type__1;
    name: string;
    submittedAt: Time;
    email: string;
    message: string;
    organization: string;
} {
    return {
        id: value.id,
        inquiryType: from_candid_Type__1_n43(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message,
        organization: value.organization
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    publishedDate: _Time;
    type: _Type;
    authorName: string;
    downloadUrl: string;
    abstract: string;
}): {
    id: bigint;
    title: string;
    publishedDate: Time;
    type: Type;
    authorName: string;
    downloadUrl: string;
    abstract: string;
} {
    return {
        id: value.id,
        title: value.title,
        publishedDate: value.publishedDate,
        type: from_candid_Type_n48(_uploadFile, _downloadFile, value.type),
        authorName: value.authorName,
        downloadUrl: value.downloadUrl,
        abstract: value.abstract
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    inquiry: null;
}): Status {
    return "active" in value ? Status.active : "completed" in value ? Status.completed : "inquiry" in value ? Status.inquiry : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceTraining: null;
} | {
    leadership: null;
} | {
    businessTransformation: null;
} | {
    professionalDevelopment: null;
} | {
    aiSkills: null;
}): Category {
    return "serviceTraining" in value ? Category.serviceTraining : "leadership" in value ? Category.leadership : "businessTransformation" in value ? Category.businessTransformation : "professionalDevelopment" in value ? Category.professionalDevelopment : "aiSkills" in value ? Category.aiSkills : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courseCustomization: null;
} | {
    corporatePartnership: null;
} | {
    enrollment: null;
} | {
    general: null;
}): Type__1 {
    return "courseCustomization" in value ? Type__1.courseCustomization : "corporatePartnership" in value ? Type__1.corporatePartnership : "enrollment" in value ? Type__1.enrollment : "general" in value ? Type__1.general : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orange: null;
} | {
    white: null;
} | {
    intelligence: null;
}): Type {
    return "orange" in value ? Type.orange : "white" in value ? Type.white : "intelligence" in value ? Type.intelligence : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Struct__5>): Array<Struct__5> {
    return value.map((x)=>from_candid_Struct__5_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Struct__3>): Array<Struct__3> {
    return value.map((x)=>from_candid_Struct__3_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Struct__2>): Array<Struct__2> {
    return value.map((x)=>from_candid_Struct__2_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Struct__6>): Array<Struct__6> {
    return value.map((x)=>from_candid_Struct__6_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Struct__1>): Array<Struct__1> {
    return value.map((x)=>from_candid_Struct__1_n46(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Struct__1_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Struct__1): _Struct__1 {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Struct__2_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Struct__2): _Struct__2 {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Struct__3_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Struct__3): _Struct__3 {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Struct__5_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Struct__5): _Struct__5 {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Struct__6_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Struct__6): _Struct__6 {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_Type__1_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expiryDate?: Time;
    description: string;
    dateGranted: Time;
    bodyName: string;
    accreditationType: string;
}): {
    id: bigint;
    expiryDate: [] | [_Time];
    description: string;
    dateGranted: _Time;
    bodyName: string;
    accreditationType: string;
} {
    return {
        id: value.id,
        expiryDate: value.expiryDate ? candid_some(value.expiryDate) : candid_none(),
        description: value.description,
        dateGranted: value.dateGranted,
        bodyName: value.bodyName,
        accreditationType: value.accreditationType
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status;
    description: string;
    customRequirements: string;
    companyName: string;
    programTitle: string;
}): {
    id: bigint;
    status: _Status;
    description: string;
    customRequirements: string;
    companyName: string;
    programTitle: string;
} {
    return {
        id: value.id,
        status: to_candid_Status_n14(_uploadFile, _downloadFile, value.status),
        description: value.description,
        customRequirements: value.customRequirements,
        companyName: value.companyName,
        programTitle: value.programTitle
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    duration: bigint;
    description: string;
    level: string;
    isCorporateCustomizable: boolean;
    category: Category;
    corporateAlignment: string;
}): {
    id: bigint;
    title: string;
    duration: bigint;
    description: string;
    level: string;
    isCorporateCustomizable: boolean;
    category: _Category;
    corporateAlignment: string;
} {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        description: value.description,
        level: value.level,
        isCorporateCustomizable: value.isCorporateCustomizable,
        category: to_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        corporateAlignment: value.corporateAlignment
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    publishedDate: Time;
    type: Type;
    authorName: string;
    downloadUrl: string;
    abstract: string;
}): {
    id: bigint;
    title: string;
    publishedDate: _Time;
    type: _Type;
    authorName: string;
    downloadUrl: string;
    abstract: string;
} {
    return {
        id: value.id,
        title: value.title,
        publishedDate: value.publishedDate,
        type: to_candid_Type_n22(_uploadFile, _downloadFile, value.type),
        authorName: value.authorName,
        downloadUrl: value.downloadUrl,
        abstract: value.abstract
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inquiryType: Type__1;
    name: string;
    submittedAt: Time;
    email: string;
    message: string;
    organization: string;
}): {
    id: bigint;
    inquiryType: _Type__1;
    name: string;
    submittedAt: _Time;
    email: string;
    message: string;
    organization: string;
} {
    return {
        id: value.id,
        inquiryType: to_candid_Type__1_n61(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message,
        organization: value.organization
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    completed: null;
} | {
    inquiry: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.inquiry ? {
        inquiry: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    serviceTraining: null;
} | {
    leadership: null;
} | {
    businessTransformation: null;
} | {
    professionalDevelopment: null;
} | {
    aiSkills: null;
} {
    return value == Category.serviceTraining ? {
        serviceTraining: null
    } : value == Category.leadership ? {
        leadership: null
    } : value == Category.businessTransformation ? {
        businessTransformation: null
    } : value == Category.professionalDevelopment ? {
        professionalDevelopment: null
    } : value == Category.aiSkills ? {
        aiSkills: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    orange: null;
} | {
    white: null;
} | {
    intelligence: null;
} {
    return value == Type.orange ? {
        orange: null
    } : value == Type.white ? {
        white: null
    } : value == Type.intelligence ? {
        intelligence: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    courseCustomization: null;
} | {
    corporatePartnership: null;
} | {
    enrollment: null;
} | {
    general: null;
} {
    return value == Type__1.courseCustomization ? {
        courseCustomization: null
    } : value == Type__1.corporatePartnership ? {
        corporatePartnership: null
    } : value == Type__1.enrollment ? {
        enrollment: null
    } : value == Type__1.general ? {
        general: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
